name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
